"""initial schema

Revision ID: 7068f2b7e1c2
Revises: 
Create Date: 2026-08-21 14:40:10.461601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7068f2b7e1c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('build_date', sa.String(length=10), nullable=False),
    sa.Column('program', sa.String(length=8), nullable=False),
    sa.Column('serial', sa.String(length=32), nullable=False),
    sa.Column('so', sa.String(length=12), nullable=False),
    sa.Column('maxop_at_log', sa.Integer(), nullable=True),
    sa.Column('sim_finish_date', sa.Date(), nullable=True),
    sa.Column('p50_date', sa.Date(), nullable=True),
    sa.Column('p80_date', sa.Date(), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('actual_close', sa.Date(), nullable=True),
    sa.Column('error_days', sa.Integer(), nullable=True),
    sa.Column('model_status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecast_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_log_build_date'), ['build_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_log_program'), ['program'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_log_serial'), ['serial'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_log_so'), ['so'], unique=False)

    op.create_table('ml_training_row',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial', sa.String(length=32), nullable=False),
    sa.Column('so', sa.String(length=12), nullable=False),
    sa.Column('program', sa.String(length=8), nullable=False),
    sa.Column('milestone_phase', sa.Integer(), nullable=True),
    sa.Column('crew_at_op', sa.Float(), nullable=True),
    sa.Column('raw_dwell_days', sa.Float(), nullable=True),
    sa.Column('cleaned_dwell_days', sa.Float(), nullable=True),
    sa.Column('wi_complexity_score', sa.Float(), nullable=True),
    sa.Column('sharedwc_queue', sa.Float(), nullable=True),
    sa.Column('sim_forecast_date', sa.Date(), nullable=True),
    sa.Column('actual_close_date', sa.Date(), nullable=True),
    sa.Column('residual_days', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_training_row', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_training_row_program'), ['program'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_training_row_serial'), ['serial'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_training_row_so'), ['so'], unique=False)

    op.create_table('model_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program', sa.String(length=8), nullable=False),
    sa.Column('model_type', sa.String(length=12), nullable=False),
    sa.Column('n_scored', sa.Integer(), nullable=False),
    sa.Column('p50_blob', sa.LargeBinary(), nullable=True),
    sa.Column('p80_blob', sa.LargeBinary(), nullable=True),
    sa.Column('bias_json', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_version_program'), ['program'], unique=False)

    op.create_table('oauth_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service', sa.String(length=16), nullable=False),
    sa.Column('access_token_enc', sa.LargeBinary(), nullable=True),
    sa.Column('refresh_token_enc', sa.LargeBinary(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service')
    )
    op.create_table('wi_constraint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program', sa.String(length=8), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=True),
    sa.Column('after_op', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('dwell_hr', sa.Float(), nullable=True),
    sa.Column('constraint_type', sa.String(length=8), nullable=False),
    sa.Column('llm_provider', sa.String(length=16), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wi_constraint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wi_constraint_program'), ['program'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wi_constraint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wi_constraint_program'))

    op.drop_table('wi_constraint')
    op.drop_table('oauth_token')
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_version_program'))

    op.drop_table('model_version')
    with op.batch_alter_table('ml_training_row', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_training_row_so'))
        batch_op.drop_index(batch_op.f('ix_ml_training_row_serial'))
        batch_op.drop_index(batch_op.f('ix_ml_training_row_program'))

    op.drop_table('ml_training_row')
    with op.batch_alter_table('forecast_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_log_so'))
        batch_op.drop_index(batch_op.f('ix_forecast_log_serial'))
        batch_op.drop_index(batch_op.f('ix_forecast_log_program'))
        batch_op.drop_index(batch_op.f('ix_forecast_log_build_date'))

    op.drop_table('forecast_log')
    # ### end Alembic commands ###
